### ISSUE TITLE
关于 CDATA 中内容问题。

### ISSUE THREAD

**Issue by SamYau2014** [dralee/FDGenericXml#1]
你好，最近我自身也在研究dotnet core中xml序列化，你的类库挺好的，帮我解决了序列化取值的问题，但是xml有中有 < ![CDATA[实际内容]]>的情况，但是我不会写对应的正则表达式，也不希望只是通过replace这种比较low的方式去解决，不知能否在下一个版本解决该问题？

**Comment by dralee** [comment]
已添加对CDATA支持，多谢支持！
